### ISSUE TITLE
Suggestion: brief git tutorial

### ISSUE THREAD

**Issue by elsandal** [BiAPoL/Bio-image_Analysis_with_Python#6]
I noticed that many students during the class are a little confused about git and github and they struggled and asked questions about how to use the course's repository, where to find the pdfs, jupyter notebooks etc. very frequently.

A brief git tutorial (like the one on conda installation and usage) might be enlightening for the students. This will not only be useful for the course but git and github are amazing tools for students, especially if they start programming for bio-imaging, bioinformatics/statistics, computational biology projects. The tutorial could be done either in the very beginning with the conda installation and focus on version control or it could be done right after the python basics.

**Comment by haesleinhuepf** [comment]
Hi @elsandal ,

that's actually a great idea. The only problem is that git typically is more complicated to explain than conda. And for python and image analysis beginners it might not be obvious what version control is good for. That's why I decided to keep this additional confusion out of the basics course and wrote the "How to use this material" section on the landing page. You may agree, following the suggestions there should work out of the box. The git-lesson will become part of the advanced course we will start likely next year. In the meantime, check out the [carpentry course about git](https://swcarpentry.github.io/git-novice/).

Thanks for the feedback though :-)

Best,
Robert
